#!/usr/bin/env python3
"""
Swagger Petstore - OpenAPI 3.0 MCP Server
Generated by mcpgen — https://github.com/JnanaSrota/mcpgen

This file is yours. Modify it freely.
mcpgen is only needed to generate this file — not to run it.

Setup:
  pip install -r requirements.txt

Run:
  python server.py
"""

import os
import json
import asyncio
import httpx
from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp import types

# ─────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────

BASE_URL = "/api/v3"

# Set this environment variable before running:
# export SWAGGER_PETSTORE_OPENAPI_3_0_TOKEN="your-token-here"
AUTH_TOKEN = os.environ.get("SWAGGER_PETSTORE_OPENAPI_3_0_TOKEN", "")
if not AUTH_TOKEN:
    print("[WARNING] SWAGGER_PETSTORE_OPENAPI_3_0_TOKEN environment variable is not set. Requests may fail.")

# ─────────────────────────────────────────────
# MCP Server
# ─────────────────────────────────────────────

app = Server("swagger-petstore---openapi-3.0")


def _build_headers() -> dict:
    """Build authentication headers."""
    headers = {"Content-Type": "application/json"}
    if AUTH_TOKEN:
        headers["Authorization"] = f"Bearer {AUTH_TOKEN}"
    return headers


# ─────────────────────────────────────────────
# Tool: add_pet
# POST /pet
# ─────────────────────────────────────────────

@app.call_tool()
async def _handle_add_pet(name: str, arguments: dict) -> list[types.TextContent]:
    if name != "add_pet":
        raise ValueError(f"Unknown tool: {name}")
    
    # Build URL
    url = BASE_URL + "/pet"
    
    # Query parameters
    query_params = {}
    
    # Request body
    body = {}
    if "name" in arguments and arguments["name"] is not None:
        body["name"] = arguments["name"]
    if "photoUrls" in arguments and arguments["photoUrls"] is not None:
        body["photoUrls"] = arguments["photoUrls"]
    if "category" in arguments and arguments["category"] is not None:
        body["category"] = arguments["category"]
    if "id" in arguments and arguments["id"] is not None:
        body["id"] = arguments["id"]
    if "status" in arguments and arguments["status"] is not None:
        body["status"] = arguments["status"]
    if "tags" in arguments and arguments["tags"] is not None:
        body["tags"] = arguments["tags"]
    
    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.post(
            url,
            params=query_params if query_params else None,
            json=body if body else None,
            headers=_build_headers(),
        )
        
        # Return raw response text — Claude will interpret it
        try:
            response.raise_for_status()
        except httpx.HTTPStatusError as e:
            return [types.TextContent(
                type="text",
                text=f"HTTP Error {e.response.status_code}: {e.response.text}"
            )]
        
        return [types.TextContent(type="text", text=response.text)]


# ─────────────────────────────────────────────
# Tool: update_pet
# PUT /pet
# ─────────────────────────────────────────────

@app.call_tool()
async def _handle_update_pet(name: str, arguments: dict) -> list[types.TextContent]:
    if name != "update_pet":
        raise ValueError(f"Unknown tool: {name}")
    
    # Build URL
    url = BASE_URL + "/pet"
    
    # Query parameters
    query_params = {}
    
    # Request body
    body = {}
    if "name" in arguments and arguments["name"] is not None:
        body["name"] = arguments["name"]
    if "photoUrls" in arguments and arguments["photoUrls"] is not None:
        body["photoUrls"] = arguments["photoUrls"]
    if "category" in arguments and arguments["category"] is not None:
        body["category"] = arguments["category"]
    if "id" in arguments and arguments["id"] is not None:
        body["id"] = arguments["id"]
    if "status" in arguments and arguments["status"] is not None:
        body["status"] = arguments["status"]
    if "tags" in arguments and arguments["tags"] is not None:
        body["tags"] = arguments["tags"]
    
    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.put(
            url,
            params=query_params if query_params else None,
            json=body if body else None,
            headers=_build_headers(),
        )
        
        # Return raw response text — Claude will interpret it
        try:
            response.raise_for_status()
        except httpx.HTTPStatusError as e:
            return [types.TextContent(
                type="text",
                text=f"HTTP Error {e.response.status_code}: {e.response.text}"
            )]
        
        return [types.TextContent(type="text", text=response.text)]


# ─────────────────────────────────────────────
# Tool: find_pets_by_status
# GET /pet/findByStatus
# ─────────────────────────────────────────────

@app.call_tool()
async def _handle_find_pets_by_status(name: str, arguments: dict) -> list[types.TextContent]:
    if name != "find_pets_by_status":
        raise ValueError(f"Unknown tool: {name}")
    
    # Build URL
    url = BASE_URL + "/pet/findByStatus"
    
    # Query parameters
    query_params = {}
    if "status" in arguments and arguments["status"] is not None:
        query_params["status"] = arguments["status"]
    
    # Request body
    body = {}
    
    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.get(
            url,
            params=query_params if query_params else None,
            json=body if body else None,
            headers=_build_headers(),
        )
        
        # Return raw response text — Claude will interpret it
        try:
            response.raise_for_status()
        except httpx.HTTPStatusError as e:
            return [types.TextContent(
                type="text",
                text=f"HTTP Error {e.response.status_code}: {e.response.text}"
            )]
        
        return [types.TextContent(type="text", text=response.text)]


# ─────────────────────────────────────────────
# Tool: find_pets_by_tags
# GET /pet/findByTags
# ─────────────────────────────────────────────

@app.call_tool()
async def _handle_find_pets_by_tags(name: str, arguments: dict) -> list[types.TextContent]:
    if name != "find_pets_by_tags":
        raise ValueError(f"Unknown tool: {name}")
    
    # Build URL
    url = BASE_URL + "/pet/findByTags"
    
    # Query parameters
    query_params = {}
    if "tags" in arguments and arguments["tags"] is not None:
        query_params["tags"] = arguments["tags"]
    
    # Request body
    body = {}
    
    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.get(
            url,
            params=query_params if query_params else None,
            json=body if body else None,
            headers=_build_headers(),
        )
        
        # Return raw response text — Claude will interpret it
        try:
            response.raise_for_status()
        except httpx.HTTPStatusError as e:
            return [types.TextContent(
                type="text",
                text=f"HTTP Error {e.response.status_code}: {e.response.text}"
            )]
        
        return [types.TextContent(type="text", text=response.text)]


# ─────────────────────────────────────────────
# Tool: get_pet_by_id
# GET /pet/{petId}
# ─────────────────────────────────────────────

@app.call_tool()
async def _handle_get_pet_by_id(name: str, arguments: dict) -> list[types.TextContent]:
    if name != "get_pet_by_id":
        raise ValueError(f"Unknown tool: {name}")
    
    # Build URL
    url = BASE_URL + "/pet/{petId}"
    if "petId" in arguments:
        url = url.replace("{ {petId} }", str(arguments["petId"]))
    
    # Query parameters
    query_params = {}
    
    # Request body
    body = {}
    
    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.get(
            url,
            params=query_params if query_params else None,
            json=body if body else None,
            headers=_build_headers(),
        )
        
        # Return raw response text — Claude will interpret it
        try:
            response.raise_for_status()
        except httpx.HTTPStatusError as e:
            return [types.TextContent(
                type="text",
                text=f"HTTP Error {e.response.status_code}: {e.response.text}"
            )]
        
        return [types.TextContent(type="text", text=response.text)]


# ─────────────────────────────────────────────
# Tool: update_pet_with_form
# POST /pet/{petId}
# ─────────────────────────────────────────────

@app.call_tool()
async def _handle_update_pet_with_form(name: str, arguments: dict) -> list[types.TextContent]:
    if name != "update_pet_with_form":
        raise ValueError(f"Unknown tool: {name}")
    
    # Build URL
    url = BASE_URL + "/pet/{petId}"
    if "petId" in arguments:
        url = url.replace("{ {petId} }", str(arguments["petId"]))
    
    # Query parameters
    query_params = {}
    if "name" in arguments and arguments["name"] is not None:
        query_params["name"] = arguments["name"]
    if "status" in arguments and arguments["status"] is not None:
        query_params["status"] = arguments["status"]
    
    # Request body
    body = {}
    
    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.post(
            url,
            params=query_params if query_params else None,
            json=body if body else None,
            headers=_build_headers(),
        )
        
        # Return raw response text — Claude will interpret it
        try:
            response.raise_for_status()
        except httpx.HTTPStatusError as e:
            return [types.TextContent(
                type="text",
                text=f"HTTP Error {e.response.status_code}: {e.response.text}"
            )]
        
        return [types.TextContent(type="text", text=response.text)]


# ─────────────────────────────────────────────
# Tool: delete_pet
# DELETE /pet/{petId}
# ─────────────────────────────────────────────

@app.call_tool()
async def _handle_delete_pet(name: str, arguments: dict) -> list[types.TextContent]:
    if name != "delete_pet":
        raise ValueError(f"Unknown tool: {name}")
    
    # Build URL
    url = BASE_URL + "/pet/{petId}"
    if "petId" in arguments:
        url = url.replace("{ {petId} }", str(arguments["petId"]))
    
    # Query parameters
    query_params = {}
    
    # Request body
    body = {}
    
    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.delete(
            url,
            params=query_params if query_params else None,
            json=body if body else None,
            headers=_build_headers(),
        )
        
        # Return raw response text — Claude will interpret it
        try:
            response.raise_for_status()
        except httpx.HTTPStatusError as e:
            return [types.TextContent(
                type="text",
                text=f"HTTP Error {e.response.status_code}: {e.response.text}"
            )]
        
        return [types.TextContent(type="text", text=response.text)]


# ─────────────────────────────────────────────
# Tool: upload_file
# POST /pet/{petId}/uploadImage
# ─────────────────────────────────────────────

@app.call_tool()
async def _handle_upload_file(name: str, arguments: dict) -> list[types.TextContent]:
    if name != "upload_file":
        raise ValueError(f"Unknown tool: {name}")
    
    # Build URL
    url = BASE_URL + "/pet/{petId}/uploadImage"
    if "petId" in arguments:
        url = url.replace("{ {petId} }", str(arguments["petId"]))
    
    # Query parameters
    query_params = {}
    if "additionalMetadata" in arguments and arguments["additionalMetadata"] is not None:
        query_params["additionalMetadata"] = arguments["additionalMetadata"]
    
    # Request body
    body = {}
    if "body" in arguments and arguments["body"] is not None:
        body["body"] = arguments["body"]
    
    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.post(
            url,
            params=query_params if query_params else None,
            json=body if body else None,
            headers=_build_headers(),
        )
        
        # Return raw response text — Claude will interpret it
        try:
            response.raise_for_status()
        except httpx.HTTPStatusError as e:
            return [types.TextContent(
                type="text",
                text=f"HTTP Error {e.response.status_code}: {e.response.text}"
            )]
        
        return [types.TextContent(type="text", text=response.text)]


# ─────────────────────────────────────────────
# Tool: get_inventory
# GET /store/inventory
# ─────────────────────────────────────────────

@app.call_tool()
async def _handle_get_inventory(name: str, arguments: dict) -> list[types.TextContent]:
    if name != "get_inventory":
        raise ValueError(f"Unknown tool: {name}")
    
    # Build URL
    url = BASE_URL + "/store/inventory"
    
    # Query parameters
    query_params = {}
    
    # Request body
    body = {}
    
    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.get(
            url,
            params=query_params if query_params else None,
            json=body if body else None,
            headers=_build_headers(),
        )
        
        # Return raw response text — Claude will interpret it
        try:
            response.raise_for_status()
        except httpx.HTTPStatusError as e:
            return [types.TextContent(
                type="text",
                text=f"HTTP Error {e.response.status_code}: {e.response.text}"
            )]
        
        return [types.TextContent(type="text", text=response.text)]


# ─────────────────────────────────────────────
# Tool: place_order
# POST /store/order
# ─────────────────────────────────────────────

@app.call_tool()
async def _handle_place_order(name: str, arguments: dict) -> list[types.TextContent]:
    if name != "place_order":
        raise ValueError(f"Unknown tool: {name}")
    
    # Build URL
    url = BASE_URL + "/store/order"
    
    # Query parameters
    query_params = {}
    
    # Request body
    body = {}
    if "complete" in arguments and arguments["complete"] is not None:
        body["complete"] = arguments["complete"]
    if "id" in arguments and arguments["id"] is not None:
        body["id"] = arguments["id"]
    if "petId" in arguments and arguments["petId"] is not None:
        body["petId"] = arguments["petId"]
    if "quantity" in arguments and arguments["quantity"] is not None:
        body["quantity"] = arguments["quantity"]
    if "shipDate" in arguments and arguments["shipDate"] is not None:
        body["shipDate"] = arguments["shipDate"]
    if "status" in arguments and arguments["status"] is not None:
        body["status"] = arguments["status"]
    
    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.post(
            url,
            params=query_params if query_params else None,
            json=body if body else None,
            headers=_build_headers(),
        )
        
        # Return raw response text — Claude will interpret it
        try:
            response.raise_for_status()
        except httpx.HTTPStatusError as e:
            return [types.TextContent(
                type="text",
                text=f"HTTP Error {e.response.status_code}: {e.response.text}"
            )]
        
        return [types.TextContent(type="text", text=response.text)]


# ─────────────────────────────────────────────
# Tool: get_order_by_id
# GET /store/order/{orderId}
# ─────────────────────────────────────────────

@app.call_tool()
async def _handle_get_order_by_id(name: str, arguments: dict) -> list[types.TextContent]:
    if name != "get_order_by_id":
        raise ValueError(f"Unknown tool: {name}")
    
    # Build URL
    url = BASE_URL + "/store/order/{orderId}"
    if "orderId" in arguments:
        url = url.replace("{ {orderId} }", str(arguments["orderId"]))
    
    # Query parameters
    query_params = {}
    
    # Request body
    body = {}
    
    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.get(
            url,
            params=query_params if query_params else None,
            json=body if body else None,
            headers=_build_headers(),
        )
        
        # Return raw response text — Claude will interpret it
        try:
            response.raise_for_status()
        except httpx.HTTPStatusError as e:
            return [types.TextContent(
                type="text",
                text=f"HTTP Error {e.response.status_code}: {e.response.text}"
            )]
        
        return [types.TextContent(type="text", text=response.text)]


# ─────────────────────────────────────────────
# Tool: delete_order
# DELETE /store/order/{orderId}
# ─────────────────────────────────────────────

@app.call_tool()
async def _handle_delete_order(name: str, arguments: dict) -> list[types.TextContent]:
    if name != "delete_order":
        raise ValueError(f"Unknown tool: {name}")
    
    # Build URL
    url = BASE_URL + "/store/order/{orderId}"
    if "orderId" in arguments:
        url = url.replace("{ {orderId} }", str(arguments["orderId"]))
    
    # Query parameters
    query_params = {}
    
    # Request body
    body = {}
    
    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.delete(
            url,
            params=query_params if query_params else None,
            json=body if body else None,
            headers=_build_headers(),
        )
        
        # Return raw response text — Claude will interpret it
        try:
            response.raise_for_status()
        except httpx.HTTPStatusError as e:
            return [types.TextContent(
                type="text",
                text=f"HTTP Error {e.response.status_code}: {e.response.text}"
            )]
        
        return [types.TextContent(type="text", text=response.text)]


# ─────────────────────────────────────────────
# Tool: create_user
# POST /user
# ─────────────────────────────────────────────

@app.call_tool()
async def _handle_create_user(name: str, arguments: dict) -> list[types.TextContent]:
    if name != "create_user":
        raise ValueError(f"Unknown tool: {name}")
    
    # Build URL
    url = BASE_URL + "/user"
    
    # Query parameters
    query_params = {}
    
    # Request body
    body = {}
    if "email" in arguments and arguments["email"] is not None:
        body["email"] = arguments["email"]
    if "firstName" in arguments and arguments["firstName"] is not None:
        body["firstName"] = arguments["firstName"]
    if "id" in arguments and arguments["id"] is not None:
        body["id"] = arguments["id"]
    if "lastName" in arguments and arguments["lastName"] is not None:
        body["lastName"] = arguments["lastName"]
    if "password" in arguments and arguments["password"] is not None:
        body["password"] = arguments["password"]
    if "phone" in arguments and arguments["phone"] is not None:
        body["phone"] = arguments["phone"]
    if "userStatus" in arguments and arguments["userStatus"] is not None:
        body["userStatus"] = arguments["userStatus"]
    if "username" in arguments and arguments["username"] is not None:
        body["username"] = arguments["username"]
    
    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.post(
            url,
            params=query_params if query_params else None,
            json=body if body else None,
            headers=_build_headers(),
        )
        
        # Return raw response text — Claude will interpret it
        try:
            response.raise_for_status()
        except httpx.HTTPStatusError as e:
            return [types.TextContent(
                type="text",
                text=f"HTTP Error {e.response.status_code}: {e.response.text}"
            )]
        
        return [types.TextContent(type="text", text=response.text)]


# ─────────────────────────────────────────────
# Tool: create_users_with_list_input
# POST /user/createWithList
# ─────────────────────────────────────────────

@app.call_tool()
async def _handle_create_users_with_list_input(name: str, arguments: dict) -> list[types.TextContent]:
    if name != "create_users_with_list_input":
        raise ValueError(f"Unknown tool: {name}")
    
    # Build URL
    url = BASE_URL + "/user/createWithList"
    
    # Query parameters
    query_params = {}
    
    # Request body
    body = {}
    if "body" in arguments and arguments["body"] is not None:
        body["body"] = arguments["body"]
    
    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.post(
            url,
            params=query_params if query_params else None,
            json=body if body else None,
            headers=_build_headers(),
        )
        
        # Return raw response text — Claude will interpret it
        try:
            response.raise_for_status()
        except httpx.HTTPStatusError as e:
            return [types.TextContent(
                type="text",
                text=f"HTTP Error {e.response.status_code}: {e.response.text}"
            )]
        
        return [types.TextContent(type="text", text=response.text)]


# ─────────────────────────────────────────────
# Tool: login_user
# GET /user/login
# ─────────────────────────────────────────────

@app.call_tool()
async def _handle_login_user(name: str, arguments: dict) -> list[types.TextContent]:
    if name != "login_user":
        raise ValueError(f"Unknown tool: {name}")
    
    # Build URL
    url = BASE_URL + "/user/login"
    
    # Query parameters
    query_params = {}
    if "password" in arguments and arguments["password"] is not None:
        query_params["password"] = arguments["password"]
    if "username" in arguments and arguments["username"] is not None:
        query_params["username"] = arguments["username"]
    
    # Request body
    body = {}
    
    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.get(
            url,
            params=query_params if query_params else None,
            json=body if body else None,
            headers=_build_headers(),
        )
        
        # Return raw response text — Claude will interpret it
        try:
            response.raise_for_status()
        except httpx.HTTPStatusError as e:
            return [types.TextContent(
                type="text",
                text=f"HTTP Error {e.response.status_code}: {e.response.text}"
            )]
        
        return [types.TextContent(type="text", text=response.text)]


# ─────────────────────────────────────────────
# Tool: logout_user
# GET /user/logout
# ─────────────────────────────────────────────

@app.call_tool()
async def _handle_logout_user(name: str, arguments: dict) -> list[types.TextContent]:
    if name != "logout_user":
        raise ValueError(f"Unknown tool: {name}")
    
    # Build URL
    url = BASE_URL + "/user/logout"
    
    # Query parameters
    query_params = {}
    
    # Request body
    body = {}
    
    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.get(
            url,
            params=query_params if query_params else None,
            json=body if body else None,
            headers=_build_headers(),
        )
        
        # Return raw response text — Claude will interpret it
        try:
            response.raise_for_status()
        except httpx.HTTPStatusError as e:
            return [types.TextContent(
                type="text",
                text=f"HTTP Error {e.response.status_code}: {e.response.text}"
            )]
        
        return [types.TextContent(type="text", text=response.text)]


# ─────────────────────────────────────────────
# Tool: get_user_by_name
# GET /user/{username}
# ─────────────────────────────────────────────

@app.call_tool()
async def _handle_get_user_by_name(name: str, arguments: dict) -> list[types.TextContent]:
    if name != "get_user_by_name":
        raise ValueError(f"Unknown tool: {name}")
    
    # Build URL
    url = BASE_URL + "/user/{username}"
    if "username" in arguments:
        url = url.replace("{ {username} }", str(arguments["username"]))
    
    # Query parameters
    query_params = {}
    
    # Request body
    body = {}
    
    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.get(
            url,
            params=query_params if query_params else None,
            json=body if body else None,
            headers=_build_headers(),
        )
        
        # Return raw response text — Claude will interpret it
        try:
            response.raise_for_status()
        except httpx.HTTPStatusError as e:
            return [types.TextContent(
                type="text",
                text=f"HTTP Error {e.response.status_code}: {e.response.text}"
            )]
        
        return [types.TextContent(type="text", text=response.text)]


# ─────────────────────────────────────────────
# Tool: update_user
# PUT /user/{username}
# ─────────────────────────────────────────────

@app.call_tool()
async def _handle_update_user(name: str, arguments: dict) -> list[types.TextContent]:
    if name != "update_user":
        raise ValueError(f"Unknown tool: {name}")
    
    # Build URL
    url = BASE_URL + "/user/{username}"
    if "username" in arguments:
        url = url.replace("{ {username} }", str(arguments["username"]))
    
    # Query parameters
    query_params = {}
    
    # Request body
    body = {}
    if "email" in arguments and arguments["email"] is not None:
        body["email"] = arguments["email"]
    if "firstName" in arguments and arguments["firstName"] is not None:
        body["firstName"] = arguments["firstName"]
    if "id" in arguments and arguments["id"] is not None:
        body["id"] = arguments["id"]
    if "lastName" in arguments and arguments["lastName"] is not None:
        body["lastName"] = arguments["lastName"]
    if "password" in arguments and arguments["password"] is not None:
        body["password"] = arguments["password"]
    if "phone" in arguments and arguments["phone"] is not None:
        body["phone"] = arguments["phone"]
    if "userStatus" in arguments and arguments["userStatus"] is not None:
        body["userStatus"] = arguments["userStatus"]
    if "username" in arguments and arguments["username"] is not None:
        body["username"] = arguments["username"]
    
    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.put(
            url,
            params=query_params if query_params else None,
            json=body if body else None,
            headers=_build_headers(),
        )
        
        # Return raw response text — Claude will interpret it
        try:
            response.raise_for_status()
        except httpx.HTTPStatusError as e:
            return [types.TextContent(
                type="text",
                text=f"HTTP Error {e.response.status_code}: {e.response.text}"
            )]
        
        return [types.TextContent(type="text", text=response.text)]


# ─────────────────────────────────────────────
# Tool: delete_user
# DELETE /user/{username}
# ─────────────────────────────────────────────

@app.call_tool()
async def _handle_delete_user(name: str, arguments: dict) -> list[types.TextContent]:
    if name != "delete_user":
        raise ValueError(f"Unknown tool: {name}")
    
    # Build URL
    url = BASE_URL + "/user/{username}"
    if "username" in arguments:
        url = url.replace("{ {username} }", str(arguments["username"]))
    
    # Query parameters
    query_params = {}
    
    # Request body
    body = {}
    
    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.delete(
            url,
            params=query_params if query_params else None,
            json=body if body else None,
            headers=_build_headers(),
        )
        
        # Return raw response text — Claude will interpret it
        try:
            response.raise_for_status()
        except httpx.HTTPStatusError as e:
            return [types.TextContent(
                type="text",
                text=f"HTTP Error {e.response.status_code}: {e.response.text}"
            )]
        
        return [types.TextContent(type="text", text=response.text)]


@app.list_tools()
async def list_tools() -> list[types.Tool]:
    """Return all available tools to Claude."""
    return [
        types.Tool(
            name="add_pet",
            description="Add a new pet to the store.",
            inputSchema={
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                    },
                    "photoUrls": {
                        "type": "array",
                    },
                    "category": {
                        "type": "object",
                    },
                    "id": {
                        "type": "integer",
                    },
                    "status": {
                        "type": "string",
"description": "pet status in the store","enum": ["available", "pending", "sold"],                    },
                    "tags": {
                        "type": "array",
                    },
                },
                "required": ["name", "photoUrls", ],
            },
        ),
        types.Tool(
            name="update_pet",
            description="Update an existing pet.",
            inputSchema={
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                    },
                    "photoUrls": {
                        "type": "array",
                    },
                    "category": {
                        "type": "object",
                    },
                    "id": {
                        "type": "integer",
                    },
                    "status": {
                        "type": "string",
"description": "pet status in the store","enum": ["available", "pending", "sold"],                    },
                    "tags": {
                        "type": "array",
                    },
                },
                "required": ["name", "photoUrls", ],
            },
        ),
        types.Tool(
            name="find_pets_by_status",
            description="Finds Pets by status.",
            inputSchema={
                "type": "object",
                "properties": {
                    "status": {
                        "type": "string",
"description": "Status values that need to be considered for filter","enum": ["available", "pending", "sold"],                    },
                },
                "required": ["status", ],
            },
        ),
        types.Tool(
            name="find_pets_by_tags",
            description="Finds Pets by tags.",
            inputSchema={
                "type": "object",
                "properties": {
                    "tags": {
                        "type": "array",
"description": "Tags to filter by",                    },
                },
                "required": ["tags", ],
            },
        ),
        types.Tool(
            name="get_pet_by_id",
            description="Find pet by ID.",
            inputSchema={
                "type": "object",
                "properties": {
                    "petId": {
                        "type": "integer",
"description": "ID of pet to return",                    },
                },
                "required": ["petId", ],
            },
        ),
        types.Tool(
            name="update_pet_with_form",
            description="Updates a pet in the store with form data.",
            inputSchema={
                "type": "object",
                "properties": {
                    "petId": {
                        "type": "integer",
"description": "ID of pet that needs to be updated",                    },
                    "name": {
                        "type": "string",
"description": "Name of pet that needs to be updated",                    },
                    "status": {
                        "type": "string",
"description": "Status of pet that needs to be updated",                    },
                },
                "required": ["petId", ],
            },
        ),
        types.Tool(
            name="delete_pet",
            description="Deletes a pet.",
            inputSchema={
                "type": "object",
                "properties": {
                    "petId": {
                        "type": "integer",
"description": "Pet id to delete",                    },
                    "api_key": {
                        "type": "string",
                    },
                },
                "required": ["petId", ],
            },
        ),
        types.Tool(
            name="upload_file",
            description="Uploads an image.",
            inputSchema={
                "type": "object",
                "properties": {
                    "petId": {
                        "type": "integer",
"description": "ID of pet to update",                    },
                    "additionalMetadata": {
                        "type": "string",
"description": "Additional Metadata",                    },
                    "body": {
                        "type": "object",
"description": "Request body",                    },
                },
                "required": ["petId", ],
            },
        ),
        types.Tool(
            name="get_inventory",
            description="Returns pet inventories by status.",
            inputSchema={
                "type": "object",
                "properties": {
                },
                "required": [],
            },
        ),
        types.Tool(
            name="place_order",
            description="Place an order for a pet.",
            inputSchema={
                "type": "object",
                "properties": {
                    "complete": {
                        "type": "boolean",
                    },
                    "id": {
                        "type": "integer",
                    },
                    "petId": {
                        "type": "integer",
                    },
                    "quantity": {
                        "type": "integer",
                    },
                    "shipDate": {
                        "type": "string",
                    },
                    "status": {
                        "type": "string",
"description": "Order Status","enum": ["placed", "approved", "delivered"],                    },
                },
                "required": [],
            },
        ),
        types.Tool(
            name="get_order_by_id",
            description="Find purchase order by ID.",
            inputSchema={
                "type": "object",
                "properties": {
                    "orderId": {
                        "type": "integer",
"description": "ID of order that needs to be fetched",                    },
                },
                "required": ["orderId", ],
            },
        ),
        types.Tool(
            name="delete_order",
            description="Delete purchase order by identifier.",
            inputSchema={
                "type": "object",
                "properties": {
                    "orderId": {
                        "type": "integer",
"description": "ID of the order that needs to be deleted",                    },
                },
                "required": ["orderId", ],
            },
        ),
        types.Tool(
            name="create_user",
            description="Create user.",
            inputSchema={
                "type": "object",
                "properties": {
                    "email": {
                        "type": "string",
                    },
                    "firstName": {
                        "type": "string",
                    },
                    "id": {
                        "type": "integer",
                    },
                    "lastName": {
                        "type": "string",
                    },
                    "password": {
                        "type": "string",
                    },
                    "phone": {
                        "type": "string",
                    },
                    "userStatus": {
                        "type": "integer",
"description": "User Status",                    },
                    "username": {
                        "type": "string",
                    },
                },
                "required": [],
            },
        ),
        types.Tool(
            name="create_users_with_list_input",
            description="Creates list of users with given input array.",
            inputSchema={
                "type": "object",
                "properties": {
                    "body": {
                        "type": "object",
"description": "Request body",                    },
                },
                "required": [],
            },
        ),
        types.Tool(
            name="login_user",
            description="Logs user into the system.",
            inputSchema={
                "type": "object",
                "properties": {
                    "password": {
                        "type": "string",
"description": "The password for login in clear text",                    },
                    "username": {
                        "type": "string",
"description": "The user name for login",                    },
                },
                "required": [],
            },
        ),
        types.Tool(
            name="logout_user",
            description="Logs out current logged in user session.",
            inputSchema={
                "type": "object",
                "properties": {
                },
                "required": [],
            },
        ),
        types.Tool(
            name="get_user_by_name",
            description="Get user by user name.",
            inputSchema={
                "type": "object",
                "properties": {
                    "username": {
                        "type": "string",
"description": "The name that needs to be fetched. Use user1 for testing",                    },
                },
                "required": ["username", ],
            },
        ),
        types.Tool(
            name="update_user",
            description="Update user resource.",
            inputSchema={
                "type": "object",
                "properties": {
                    "username": {
                        "type": "string",
"description": "name that need to be deleted",                    },
                    "email": {
                        "type": "string",
                    },
                    "firstName": {
                        "type": "string",
                    },
                    "id": {
                        "type": "integer",
                    },
                    "lastName": {
                        "type": "string",
                    },
                    "password": {
                        "type": "string",
                    },
                    "phone": {
                        "type": "string",
                    },
                    "userStatus": {
                        "type": "integer",
"description": "User Status",                    },
                    "username": {
                        "type": "string",
                    },
                },
                "required": ["username", ],
            },
        ),
        types.Tool(
            name="delete_user",
            description="Delete user resource.",
            inputSchema={
                "type": "object",
                "properties": {
                    "username": {
                        "type": "string",
"description": "The name that needs to be deleted",                    },
                },
                "required": ["username", ],
            },
        ),
    ]


if __name__ == "__main__":
    asyncio.run(stdio_server(app))